
name: Azure Python 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.19
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.19
    - name: Install dependences
      run: |
        make install-azure
    - name: Lint with Pylint
      run: |
        make lint
    - name: Test with Pytest
      run: |
        make test
